MAX_TSP_EXACT_NODES = 12
MAX_TSP_DESTINATIONS = 100
MAX_DIJKSTRA_NODES = 120
MAX_DIJKSTRA_NEIGHBORS = 20
MAX_TRAVERSAL_NODES = 120
MAX_TRAVERSAL_NEIGHBORS = 20
MAX_BACKTRACKING_NODES = 10
MAX_BACKTRACKING_VISITS = 10
MAX_SECTOR_SIZE_ALLOWED = 50
MAX_SECTORIZATION_NODES = 500
MAX_SECTORIZATION_DEPTH = 12

